name: Run lit llama

on:
  push:
  pull_request:

jobs:
  review:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Python environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: clone repo
        run: |
            git clone https://github.com/Lightning-AI/lit-llama
            cd lit-llama
            
      - name: install dependencies
        run: |
            pip install requirements.txt
            
      - name: Run lit-llama
        run: |
            python generate.py --prompt "Hello, my name is"
        
        
